title: <p align="center"> Alok Narayan </p>
logo: /assets/img/Profile_photo.jpg
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alok-narayan-6054a315/">LinkedIn</a> |
  <a href="https://github.com/aloknarayan23">GitHub</a>
  
  <br>   
  I'm learning Machine learning & AI at IIIT Bangalore.
  Currently working in Mercedes-Benz Research and Development,India.
  Worked with Forvia India.
  <br>
  </p>
  
  
  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
